import { UserProvider } from '@/contexts';
import './globals.css';
import Navigation from '@/components/Navigation';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="light">
			<body>
				<UserProvider>
					<Navigation />
					{children}
				</UserProvider>
			</body>
		</html>
	);
}
